version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: tms
      POSTGRES_USER: tms
      POSTGRES_PASSWORD: tms
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -lc "python3 manage.py migrate && python3 manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/staticfiles
    environment:
      DATABASE_URL: postgres://tms:tms@postgres:5432/tms
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: prod-secret
      DEBUG: 'False'
      ALLOWED_HOSTS: '*'
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://tms:tms@postgres:5432/tms
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: prod-secret
      DEBUG: 'False'
    depends_on:
      - postgres
      - redis

  beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://tms:tms@postgres:5432/tms
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: prod-secret
      DEBUG: 'False'
    depends_on:
      - postgres
      - redis

volumes:
  pg_data:
  media_data:
  static_data: